
export const topDealUsers:any[] = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
      username: "Elva McDonald",
      email: "elva@gmail.com",
      amount: "3.668",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Linnie Nelson",
      email: "linnie@gmail.com",
      amount: "3.256",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Brent Reeves",
      email: "brent@gmail.com",
      amount: "2.998",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Adeline Watson",
      email: "adeline@gmail.com",
      amount: "2.512",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Juan Harrington",
      email: "juan@gmail.com",
      amount: "2.134",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Augusta McGee",
      email: "augusta@gmail.com",
      amount: "1.932",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600",
      username: "Angel Thomas",
      email: "angel@gmail.com",
      amount: "1.560",
    },
  ];

  export const dummyUsers = [

      {
        name: 'John Doe',
        username: 'johndoe123',
        productsBought: 45,
        amountSpent: 2345.67,
        role: 'user',
      },
      {
        name: 'Jane Smith',
        username: 'janesmith456',
        productsBought: 32,
        amountSpent: 1234.56,
        role: 'user',
      },
      {
        name: 'David Johnson',
        username: 'davidj82',
        productsBought: 58,
        amountSpent: 3789.12,
        role: 'admin',
      },
      {
        name: 'Emily Davis',
        username: 'emilydavis789',
        productsBought: 22,
        amountSpent: 1112.34,
        role: 'user',
      },
      {
        name: 'Michael Brown',
        username: 'mikebrown55',
        productsBought: 65,
        amountSpent: 4567.89,
        role: 'user',
      },
      {
        name: 'Sarah Wilson',
        username: 'sarahw23',
        productsBought: 12,
        amountSpent: 678.90,
        role: 'user',
      },
      {
        name: 'Kevin Lee',
        username: 'kevinl77',
        productsBought: 41,
        amountSpent: 2234.50,
        role: 'user',
      },
      {
        name: 'Jessica White',
        username: 'jessicawhite12',
        productsBought: 53,
        amountSpent: 3456.78,
        role: 'user',
      },
      {
        name: 'Robert Taylor',
        username: 'robtaylor33',
        productsBought: 19,
        amountSpent: 987.65,
        role: 'user',
      },
      {
        name: 'Amanda Moore',
        username: 'amandam345',
        productsBought: 37,
        amountSpent: 1999.99,
        role: 'user',
      },
      
      {
        name: 'John Doe',
        username: 'johndoe123',
        productsBought: 45,
        amountSpent: 2345.67,
        role: 'user',
      },
      {
        name: 'Jane Smith',
        username: 'janesmith456',
        productsBought: 32,
        amountSpent: 1234.56,
        role: 'user',
      },
      {
        name: 'David Johnson',
        username: 'davidj82',
        productsBought: 58,
        amountSpent: 3789.12,
        role: 'admin',
      },
      {
        name: 'Emily Davis',
        username: 'emilydavis789',
        productsBought: 22,
        amountSpent: 1112.34,
        role: 'user',
      },
      {
        name: 'Michael Brown',
        username: 'mikebrown55',
        productsBought: 65,
        amountSpent: 4567.89,
        role: 'user',
      },
      {
        name: 'Sarah Wilson',
        username: 'sarahw23',
        productsBought: 12,
        amountSpent: 678.90,
        role: 'user',
      },
      {
        name: 'Kevin Lee',
        username: 'kevinl77',
        productsBought: 41,
        amountSpent: 2234.50,
        role: 'user',
      },
      {
        name: 'Jessica White',
        username: 'jessicawhite12',
        productsBought: 53,
        amountSpent: 3456.78,
        role: 'user',
      },
      {
        name: 'Robert Taylor',
        username: 'robtaylor33',
        productsBought: 19,
        amountSpent: 987.65,
        role: 'user',
      },
      {
        name: 'Amanda Moore',
        username: 'amandam345',
        productsBought: 37,
        amountSpent: 1999.99,
        role: 'user',
      },
    ];
    
   

 